import React, { useMemo } from 'react';
import { useGradeManagementContext } from '../../../contexts/GradeManagementContext';
import { EditableCell } from './EditableCell';
export const Spreadsheet: React.FC = () => {
  const { state, dispatch } = useGradeManagementContext();
  const assessments = useMemo(() => [...state.assessments].filter(item => item.status === 'active').sort((a, b) => a.displayOrder - b.displayOrder), [state.assessments]);
  const students = state.students.filter(student => `${student.name} ${student.studentNumber}`.toLowerCase().includes(state.searchTerm.toLowerCase()));
  const scores = new Map(state.studentScores.map(score => [`${score.studentId}:${score.assessmentId}`, score.score]));
  if (!state.subjectCode) return <p className="p-8 text-center text-slate-500">Choose a subject and section to load its class record.</p>;
  return <div className="overflow-auto rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900"><table className="min-w-max w-full text-sm"><thead className="sticky top-0 z-20 bg-violet-50 text-slate-700 dark:bg-slate-800 dark:text-slate-100"><tr><th className="sticky left-0 z-30 min-w-48 border-b p-3 text-left">Student</th>{assessments.map(assessment => <th key={assessment.id} className="min-w-28 border-b p-3 text-center"><span className="block font-semibold">{assessment.name}</span><span className="text-xs font-normal text-slate-500">{assessment.category} · /{assessment.maxScore}</span></th>)}<th className="sticky right-0 z-30 border-b bg-violet-50 p-3 dark:bg-slate-800">Weighted %</th><th className="sticky right-0 z-30 border-b bg-violet-50 p-3 dark:bg-slate-800">GWA</th><th className="sticky right-0 z-30 border-b bg-violet-50 p-3 dark:bg-slate-800">Status</th></tr></thead><tbody>{students.map(student => { const grade = state.computedGrades.find(item => item.studentId === student.id); return <tr key={student.id} className="hover:bg-emerald-50/60 dark:hover:bg-emerald-950/20"><td className="sticky left-0 z-10 cursor-pointer border-b bg-white p-3 dark:bg-slate-900" onClick={() => { dispatch({ type: 'SET_SELECTED_STUDENT', payload: student.id }); dispatch({ type: 'TOGGLE_UI', payload: { key: 'showStudentSummaryDrawer', value: true } }); }}><span className="block font-medium">{student.name}</span><span className="text-xs text-slate-500">{student.studentNumber}</span></td>{assessments.map(assessment => <td className="border-b p-2 text-center" key={assessment.id}><EditableCell studentId={student.id} assessmentId={assessment.id} maxScore={assessment.maxScore} initialValue={scores.get(`${student.id}:${assessment.id}`) ?? null}/></td>)}<td className="sticky right-0 z-10 border-b bg-white p-3 text-center dark:bg-slate-900">{grade ? `${grade.weightedPercentage.toFixed(2)}%` : '—'}</td><td className="sticky right-0 z-10 border-b bg-white p-3 text-center dark:bg-slate-900">{grade?.gwa.toFixed(2) ?? '—'}</td><td className="sticky right-0 z-10 border-b bg-white p-3 text-center dark:bg-slate-900">{grade?.retentionStatus ?? 'Incomplete'}</td></tr>; })}</tbody></table>{students.length === 0 && <p className="p-8 text-center text-slate-500">No authorized students match this search.</p>}</div>;
};
