import React from 'react';
import { Download, FileUp, Plus, Printer, Save, Settings2, ShieldCheck, Unlock } from 'lucide-react';
import { useGradeManagementContext } from '../../../contexts/GradeManagementContext';
export const Toolbar: React.FC = () => {
  const { state, dispatch, saveWorkspace, canPublish, canReopen, reopenWorkspace } = useGradeManagementContext();
  const open = (key: 'showAssessmentDrawer' | 'showWeightDrawer' | 'showImportDialog' | 'showExportDialog' | 'showPublishDialog') => dispatch({ type: 'TOGGLE_UI', payload: { key, value: true } });
  const reopen = async () => { const reason = window.prompt('Reason for reopening this published class record:'); if (reason) await reopenWorkspace(reason); };
  const button = 'inline-flex items-center gap-1 rounded-lg border px-3 py-2 text-sm font-semibold transition hover:bg-slate-50 disabled:cursor-not-allowed disabled:opacity-50 dark:hover:bg-slate-800';
  const status = state.isReadOnly ? 'Published - read only' : state.autosaveStatus === 'saving' ? 'Auto-saving...' : state.lastSaved ? `Saved at ${state.lastSaved.toLocaleTimeString()}` : 'Unsaved';
  return <div className="flex flex-wrap items-center gap-2 rounded-2xl border border-slate-200 bg-white p-3 shadow-sm dark:border-slate-800 dark:bg-slate-900"><button className={button} onClick={() => open('showAssessmentDrawer')} disabled={state.isReadOnly}><Plus size={16}/> Assessments</button><button className={button} onClick={() => open('showWeightDrawer')} disabled={state.isReadOnly}><Settings2 size={16}/> Weights</button><button className={button} onClick={() => void saveWorkspace()} disabled={state.isReadOnly}><Save size={16}/> Save draft</button><button className={button} onClick={() => open('showImportDialog')} disabled={state.isReadOnly}><FileUp size={16}/> Import</button><button className={button} onClick={() => open('showExportDialog')}><Download size={16}/> Export</button><button className={button} onClick={() => window.print()}><Printer size={16}/> Print</button>{state.isReadOnly ? <button className={button} onClick={() => void reopen()} disabled={!canReopen}><Unlock size={16}/> Reopen</button> : <button className={`${button} border-emerald-600 bg-emerald-600 text-white hover:bg-emerald-700`} onClick={() => open('showPublishDialog')} disabled={!canPublish}><ShieldCheck size={16}/> Publish</button>}<span className="ml-auto text-xs font-medium text-slate-500">{status}</span></div>;
};
