import React, { useEffect, useMemo, useState } from 'react';
import { Activity, AlertTriangle, CheckCircle2, Download, FileText, Filter, Search, ShieldCheck, SlidersHorizontal, XCircle } from 'lucide-react';
import { auditForCurrentUser, AuditLog, AuditRole, AuditStatus } from '../services/auditService';
import { getAdminAuditLogsApi } from '../services/apiClient';
import { Card, CardContent, CardHeader, CardTitle } from './Card';
import { Modal } from './Modal';

type Props = { role: AuditRole; title: string; subtitle: string; allLogs?: boolean; accent: 'accent' | 'clinical' | 'blue' };
const themes = {
  accent: { button: 'bg-accent-600 hover:bg-accent-700', icon: 'text-accent-500', surface: 'border-accent-200/60 bg-accent-50/50 dark:border-accent-900/30 dark:bg-accent-950/15' },
  clinical: { button: 'bg-clinical-600 hover:bg-clinical-700', icon: 'text-clinical-500', surface: 'border-clinical-200/60 bg-clinical-50/50 dark:border-clinical-900/30 dark:bg-clinical-950/15' },
  blue: { button: 'bg-blue-600 hover:bg-blue-700', icon: 'text-blue-500', surface: 'border-blue-200/60 bg-blue-50/50 dark:border-blue-900/30 dark:bg-blue-950/15' },
};
const statusClass: Record<AuditStatus, string> = { Success: 'bg-emerald-50 text-emerald-700 dark:bg-emerald-950/30 dark:text-emerald-400', Warning: 'bg-amber-50 text-amber-700 dark:bg-amber-950/30 dark:text-amber-400', Failed: 'bg-rose-50 text-rose-700 dark:bg-rose-950/30 dark:text-rose-400' };

export const AuditTrailPage: React.FC<Props> = ({ role, title, subtitle, allLogs = false, accent }) => {
  const theme = themes[accent]; const [query, setQuery] = useState(''); const [roleFilter, setRoleFilter] = useState('all'); const [moduleFilter, setModuleFilter] = useState('all'); const [statusFilter, setStatusFilter] = useState('all'); const [date, setDate] = useState(''); const [sort, setSort] = useState<'newest' | 'oldest'>('newest'); const [selected, setSelected] = useState<AuditLog | null>(null);
  const [dbLogs, setDbLogs] = useState<AuditLog[]>([]);

  useEffect(() => {
    getAdminAuditLogsApi({ query, role: roleFilter, module: moduleFilter, status: statusFilter, date })
      .then((data) => {
        if (Array.isArray(data) && data.length > 0) {
          setDbLogs(data as AuditLog[]);
        }
      })
      .catch(() => {});
  }, [query, roleFilter, moduleFilter, statusFilter, date]);

  const source = dbLogs.length > 0 ? dbLogs : auditForCurrentUser();
  const logs = allLogs ? source : source.filter(log => log.userRole === role); const modules = Array.from(new Set(logs.map(log => log.module))).sort();
  const filtered = useMemo(() => logs.filter(log => (!query || `${log.userName} ${log.action}`.toLowerCase().includes(query.toLowerCase())) && (roleFilter === 'all' || log.userRole === roleFilter) && (moduleFilter === 'all' || log.module === moduleFilter) && (statusFilter === 'all' || log.status === statusFilter) && (!date || log.timestamp.startsWith(date))).sort((a, b) => sort === 'newest' ? b.timestamp.localeCompare(a.timestamp) : a.timestamp.localeCompare(b.timestamp)), [logs, query, roleFilter, moduleFilter, statusFilter, date, sort]);
  const exportCsv = () => { const rows = [['Timestamp', 'User', 'Role', 'Action', 'Module', 'Description', 'Status', 'IP Address', 'Device'], ...filtered.map(log => [log.timestamp, log.userName, log.userRole, log.action, log.module, log.description, log.status, log.ipAddress, log.device])]; const csv = rows.map(row => row.map(value => `"${String(value).replaceAll('"', '""')}"`).join(',')).join('\n'); const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([csv], { type: 'text/csv' })); link.download = `dentisys-audit-trail-${new Date().toISOString().slice(0, 10)}.csv`; link.click(); URL.revokeObjectURL(link.href); };
  const cards = [
    { label: 'Success', count: logs.filter(log => log.status === 'Success').length, icon: CheckCircle2, iconClass: theme.icon, surface: theme.surface },
    { label: 'Warning', count: logs.filter(log => log.status === 'Warning').length, icon: AlertTriangle, iconClass: 'text-amber-500', surface: 'border-amber-200/60 bg-amber-50/50 dark:border-amber-900/30 dark:bg-amber-950/15' },
    { label: 'Failed', count: logs.filter(log => log.status === 'Failed').length, icon: XCircle, iconClass: 'text-rose-500', surface: 'border-rose-200/60 bg-rose-50/50 dark:border-rose-900/30 dark:bg-rose-950/15' },
    { label: 'All activity', count: logs.length, icon: Activity, iconClass: theme.icon, surface: theme.surface },
  ];
  return <div className="space-y-6 animate-fade-in max-w-7xl mx-auto">
    <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 border-b border-slate-200 dark:border-slate-800 pb-4"><div><h1 className="text-2xl font-extrabold font-heading text-slate-800 dark:text-slate-100">{title}</h1><p className="text-xs text-slate-400 mt-1">{subtitle}</p></div><div className="flex gap-2 no-print"><button onClick={exportCsv} className="flex items-center gap-1.5 px-3.5 py-2.5 rounded-xl border border-slate-200 dark:border-slate-800 text-xs font-bold text-slate-600 dark:text-slate-300"><Download className="w-4 h-4" />Export CSV</button><button onClick={() => window.print()} className={`flex items-center gap-1.5 px-3.5 py-2.5 rounded-xl text-white text-xs font-bold ${theme.button}`}><FileText className="w-4 h-4" />Print PDF</button></div></div>
    <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 no-print">{cards.map(({ label, count, icon: Icon, iconClass, surface }) => <Card key={label} className={`p-4 flex items-center justify-between border ${surface}`}><div><p className="text-[10px] uppercase tracking-wider font-bold text-slate-400">{label}</p><p className="text-2xl font-extrabold text-slate-800 dark:text-slate-100 mt-1">{count}</p></div><div className={`p-2.5 rounded-xl bg-white/70 dark:bg-slate-900/60 ${iconClass}`}><Icon className="w-5 h-5" /></div></Card>)}</div>
    <Card className="no-print"><CardContent className="p-4"><div className="flex flex-wrap gap-3 items-center"><Filter className={`w-4 h-4 ${theme.icon}`} /><div className="relative"><Search className="w-3.5 h-3.5 absolute left-2.5 top-1/2 -translate-y-1/2 text-slate-400" /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search user or action..." className="pl-8 pr-3 py-2 rounded-xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-950 text-xs w-48" /></div>{allLogs && <Select value={roleFilter} onChange={setRoleFilter} options={['all', 'admin', 'faculty', 'secretary']} />}<Select value={moduleFilter} onChange={setModuleFilter} options={['all', ...modules]} /><Select value={statusFilter} onChange={setStatusFilter} options={['all', 'Success', 'Warning', 'Failed']} /><input type="date" value={date} onChange={event => setDate(event.target.value)} className="px-3 py-2 rounded-xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-950 text-xs" /><button onClick={() => setSort(sort === 'newest' ? 'oldest' : 'newest')} className={`flex items-center gap-1.5 px-3 py-2 rounded-xl border text-xs font-bold ${theme.surface}`}><SlidersHorizontal className="w-3.5 h-3.5" />{sort === 'newest' ? 'Newest first' : 'Oldest first'}</button><span className="ml-auto text-[10px] text-slate-400 font-semibold">{filtered.length} logs</span></div></CardContent></Card>
    <Card className="p-0 overflow-hidden"><CardHeader className="border-b border-slate-100 dark:border-slate-800/80"><CardTitle className="flex items-center gap-2 text-sm"><ShieldCheck className={`w-4.5 h-4.5 ${theme.icon}`} />Activity records</CardTitle></CardHeader><CardContent className="p-0 overflow-x-auto"><table className="w-full min-w-[900px] text-left text-xs"><thead className="bg-slate-50/80 dark:bg-slate-900/50"><tr className="text-[9px] uppercase tracking-wider font-bold text-slate-400"><th className="px-5 py-3">Timestamp</th><th className="px-5 py-3">User</th><th className="px-5 py-3">Action</th><th className="px-5 py-3">Module</th><th className="px-5 py-3">Status</th><th className="px-5 py-3 text-right">Details</th></tr></thead><tbody className="divide-y divide-slate-100 dark:divide-slate-800/60">{filtered.map(log => <tr key={log.id} className="hover:bg-slate-50/60 dark:hover:bg-slate-900/30"><td className="px-5 py-3 text-slate-500 whitespace-nowrap">{new Date(log.timestamp).toLocaleString()}</td><td className="px-5 py-3"><p className="font-bold text-slate-800 dark:text-slate-200">{log.userName}</p><p className="text-[10px] text-slate-400 capitalize">{log.userRole}</p></td><td className="px-5 py-3 font-semibold text-slate-700 dark:text-slate-300">{log.action}</td><td className="px-5 py-3 text-slate-500">{log.module}</td><td className="px-5 py-3"><span className={`px-2 py-0.5 rounded-md text-[9px] font-extrabold uppercase ${statusClass[log.status]}`}>{log.status}</span></td><td className="px-5 py-3 text-right"><button onClick={() => setSelected(log)} className={`text-[10px] font-bold ${theme.icon}`}>View details</button></td></tr>)}{filtered.length === 0 && <tr><td colSpan={6} className="px-5 py-10 text-center text-slate-400">No audit records match the selected filters.</td></tr>}</tbody></table></CardContent></Card>
    <Modal isOpen={Boolean(selected)} onClose={() => setSelected(null)} title="Audit log details"><div className="grid grid-cols-2 gap-4 text-xs">{selected && Object.entries({ Timestamp: new Date(selected.timestamp).toLocaleString(), User: selected.userName, Role: selected.userRole, Action: selected.action, Module: selected.module, Status: selected.status, 'IP address': selected.ipAddress, Device: selected.device, Description: selected.description }).map(([label, value]) => <div key={label} className={label === 'Description' || label === 'Device' ? 'col-span-2' : ''}><p className="text-[10px] uppercase tracking-wider font-bold text-slate-400">{label}</p><p className="mt-1 font-medium text-slate-700 dark:text-slate-300 break-words">{value}</p></div>)}</div></Modal>
  </div>;
};
const Select = ({ value, onChange, options }: { value: string; onChange: (value: string) => void; options: string[] }) => <select value={value} onChange={event => onChange(event.target.value)} className="px-3 py-2 rounded-xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-950 text-xs text-slate-600 dark:text-slate-300">{options.map(option => <option key={option} value={option}>{option === 'all' ? 'All' : option}</option>)}</select>;
