import React, { useState } from 'react';
import toast from 'react-hot-toast';
import { Modal } from '../../shared/Modal/Modal';
import { useGradeManagementContext } from '../../../contexts/GradeManagementContext';
type CsvRow = { studentId: string; assessmentId: string; score: string };
const parseCsv = (text: string): CsvRow[] => { const [header, ...lines] = text.trim().split(/\r?\n/); const columns = header.split(',').map(value => value.trim()); return lines.filter(Boolean).map(line => { const values = line.split(',').map(value => value.trim()); return { studentId: values[columns.indexOf('studentId')] ?? '', assessmentId: values[columns.indexOf('assessmentId')] ?? '', score: values[columns.indexOf('score')] ?? '' }; }); };
export const ImportDialog: React.FC = () => {
  const { state, dispatch } = useGradeManagementContext(); const [preview, setPreview] = useState<CsvRow[]>([]); const [issues, setIssues] = useState<string[]>([]);
  const close = () => { dispatch({ type: 'TOGGLE_UI', payload: { key: 'showImportDialog', value: false } }); setPreview([]); setIssues([]); };
  const read = async (file: File) => { const rows = parseCsv(await file.text()); const errors: string[] = []; const seen = new Set<string>(); rows.forEach((row, index) => { const assessment = state.assessments.find(item => item.id === row.assessmentId); const key = `${row.studentId}:${row.assessmentId}`; if (!state.students.some(student => student.id === row.studentId)) errors.push(`Row ${index + 2}: unknown student.`); if (!assessment) errors.push(`Row ${index + 2}: unknown assessment.`); if (seen.has(key)) errors.push(`Row ${index + 2}: duplicate score.`); seen.add(key); const score = Number(row.score); if (row.score !== '' && (!Number.isFinite(score) || score < 0 || (assessment && score > assessment.maxScore))) errors.push(`Row ${index + 2}: score is invalid.`); }); setPreview(rows); setIssues(errors); };
  const apply = () => { if (!preview.length || issues.length) return; const imported = preview.map(row => ({ studentId: row.studentId, assessmentId: row.assessmentId, score: row.score === '' ? null : Number(row.score) })); const map = new Map(state.studentScores.map(score => [`${score.studentId}:${score.assessmentId}`, score])); imported.forEach(score => map.set(`${score.studentId}:${score.assessmentId}`, score)); dispatch({ type: 'SET_STATE', payload: { studentScores: [...map.values()] } }); toast.success(`${imported.length} score${imported.length === 1 ? '' : 's'} imported.`); close(); };
  return <Modal open={state.showImportDialog} onClose={close} title="Import grade sheet"><div className="space-y-4 text-sm"><p>Upload a CSV with <code>studentId</code>, <code>assessmentId</code>, and <code>score</code> columns. Existing matching scores will be overwritten only after validation.</p><input type="file" accept=".csv,text/csv" onChange={event => { const file = event.target.files?.[0]; if (file) void read(file); }}/>{preview.length > 0 && <p className="rounded bg-slate-50 p-2">Preview: {preview.length} row(s).</p>}{issues.length > 0 && <ul className="rounded bg-rose-50 p-3 text-rose-700">{issues.slice(0, 5).map(issue => <li key={issue}>• {issue}</li>)}</ul>}<div className="flex justify-end gap-2"><button className="rounded border px-3 py-2" onClick={close}>Cancel</button><button className="rounded bg-emerald-600 px-3 py-2 font-semibold text-white disabled:opacity-50" disabled={!preview.length || issues.length > 0} onClick={apply}>Import validated scores</button></div></div></Modal>;
};
