import React from 'react';
import { Search } from 'lucide-react';

export type EmailLog = { id: string; recipient: string; subject: string; type: 'Privacy Consent' | 'At-Risk Notification'; sentAt: string; status: 'Sent' | 'Failed' | 'Pending' };

export const EmailHistoryTable: React.FC<{ logs: EmailLog[]; search: string; onSearch: (value: string) => void; filter: string; onFilter: (value: string) => void }> = ({ logs, search, onSearch, filter, onFilter }) => {
  const visible = logs.filter(log => (filter === 'all' || log.type === filter) && `${log.recipient} ${log.subject}`.toLowerCase().includes(search.toLowerCase()));
  return <>
    <div className="flex flex-col sm:flex-row gap-3 mb-5"><label className="relative flex-1"><Search className="w-4 h-4 absolute left-3 top-3 text-slate-400" /><input value={search} onChange={e => onSearch(e.target.value)} placeholder="Search recipient or subject" className="w-full pl-9 pr-3 py-2.5 rounded-xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 text-sm" /></label><select value={filter} onChange={e => onFilter(e.target.value)} className="px-3 py-2.5 rounded-xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 text-sm"><option value="all">All email types</option><option>Privacy Consent</option><option>At-Risk Notification</option></select></div>
    <div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead><tr className="border-b border-slate-100 dark:border-slate-800 text-slate-400 uppercase tracking-wide"><th className="p-3">Recipient</th><th className="p-3">Subject</th><th className="p-3">Type</th><th className="p-3">Date sent</th><th className="p-3">Status</th></tr></thead><tbody className="divide-y divide-slate-100 dark:divide-slate-800">{visible.map(log => <tr key={log.id}><td className="p-3 font-semibold text-slate-700 dark:text-slate-200">{log.recipient}</td><td className="p-3 text-slate-500">{log.subject}</td><td className="p-3">{log.type}</td><td className="p-3 text-slate-500">{log.sentAt}</td><td className="p-3"><span className={`px-2 py-1 rounded-full font-bold ${log.status === 'Sent' ? 'bg-emerald-100 text-emerald-700' : log.status === 'Failed' ? 'bg-rose-100 text-rose-700' : 'bg-amber-100 text-amber-700'}`}>{log.status}</span></td></tr>)}</tbody></table>{visible.length === 0 && <p className="text-center py-8 text-slate-400">No emails match your filters.</p>}</div>
  </>;
};
