-- =============================================================================

CREATE EXTENSION IF NOT EXISTS citext;
-- DentiSys Baseline Schema — 15 Application Tables + seed infrastructure
-- Stage 1: Clean database only. No users, passwords, tokens, or secrets.
-- Table order ensures all FK targets exist before their dependents.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 1. user_accounts
-- Central identity: credentials, role, profile, preferences, account state.
-- No foreign keys.
-- ---------------------------------------------------------------------------
CREATE TABLE user_accounts (
    user_id          INTEGER GENERATED BY DEFAULT AS IDENTITY,
    login_email      VARCHAR(255)    NOT NULL,
    password_hash    VARCHAR(255)    NOT NULL,
    role             TEXT NOT NULL,
    display_name     VARCHAR(255)    NOT NULL,
    title            VARCHAR(255)    NULL,
    status           VARCHAR(20)     NOT NULL DEFAULT 'Active',
    token_version    INTEGER    NOT NULL DEFAULT 0,
    theme            TEXT NOT NULL DEFAULT 'light',
    created_at       TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at       TIMESTAMP(6)     NULL DEFAULT NULL,
    approved_at      TIMESTAMP(6)     NULL,
    rejected_at      TIMESTAMP(6)     NULL,
    disabled_at      TIMESTAMP(6)     NULL,
    PRIMARY KEY (user_id),
    CONSTRAINT uq_user_accounts_login_email UNIQUE (login_email)
);


-- ---------------------------------------------------------------------------
-- 2. role_permissions
-- Denormalized RBAC policy.  Missing rows = deny.
-- No foreign keys.
-- ---------------------------------------------------------------------------
CREATE TABLE role_permissions (
    rp_id      INTEGER GENERATED BY DEFAULT AS IDENTITY,
    role_name  TEXT NOT NULL,
    resource   VARCHAR(100)    NOT NULL,
    action     VARCHAR(50)     NOT NULL,
    scope      TEXT NOT NULL,
    PRIMARY KEY (rp_id),
    CONSTRAINT uq_role_permissions UNIQUE (role_name, resource, action, scope)
);


-- ---------------------------------------------------------------------------
-- 3. courses
-- Course catalog with grading component configuration stored as JSON.
-- No foreign keys (FKs inbound from class_sections).
-- ---------------------------------------------------------------------------
CREATE TABLE courses (
    course_id    INTEGER GENERATED BY DEFAULT AS IDENTITY,
    course_code  VARCHAR(50)     NOT NULL,
    name         VARCHAR(255)    NOT NULL,
    units        DECIMAL(3,1)    NOT NULL,
    year_level   SMALLINT NULL,
    semester     TEXT NULL,
    description  TEXT            NULL,
    is_clinical  SMALLINT      NOT NULL DEFAULT 0,
    grading_config JSONB NOT NULL,
    has_zero_rule SMALLINT     NOT NULL DEFAULT 0,
    created_at   TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (course_id),
    CONSTRAINT uq_courses_course_code UNIQUE (course_code)
);


-- ---------------------------------------------------------------------------
-- 4. class_sections
-- A course offering: one course taught by one instructor in one term, with
-- an optional assigned secretary.
-- FKs: courses (must exist), user_accounts (must exist).
-- ---------------------------------------------------------------------------
CREATE TABLE class_sections (
    cs_id             INTEGER GENERATED BY DEFAULT AS IDENTITY,
    cs_name           VARCHAR(255)    NOT NULL,
    course_id         INTEGER    NOT NULL,
    instructor_user_id INTEGER   NOT NULL,
    secretary_user_id INTEGER    NULL,
    semester          TEXT NOT NULL,
    school_year       VARCHAR(20)     NOT NULL,
    year_level        SMALLINT NULL,
    lab_room          VARCHAR(100)    NULL,
    lec_room          VARCHAR(100)    NULL,
    block             VARCHAR(50)     NULL,
    status            VARCHAR(20)     NOT NULL DEFAULT 'Active',
    term_code         VARCHAR(50)     NULL,
    term_start_date   DATE            NULL,
    term_end_date     DATE            NULL,
    created_at        TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (cs_id),
    CONSTRAINT fk_cs_course FOREIGN KEY (course_id)
        REFERENCES courses (course_id)
        ON DELETE RESTRICT
        ON UPDATE RESTRICT,
    CONSTRAINT fk_cs_instructor FOREIGN KEY (instructor_user_id)
        REFERENCES user_accounts (user_id)
        ON DELETE RESTRICT
        ON UPDATE RESTRICT,
    CONSTRAINT fk_cs_secretary FOREIGN KEY (secretary_user_id)
        REFERENCES user_accounts (user_id)
        ON DELETE SET NULL
        ON UPDATE RESTRICT
);


-- ---------------------------------------------------------------------------
-- 5. students
-- Student identity, demographics, and optional link to a user account.
-- students.user_id is the authoritative link when a student is activated as
-- a Class Secretary.
-- FK: user_accounts (nullable).
-- ---------------------------------------------------------------------------
CREATE TABLE students (
    student_id     INTEGER GENERATED BY DEFAULT AS IDENTITY,
    student_number VARCHAR(50)     NOT NULL,
    first_name     VARCHAR(100)    NOT NULL,
    last_name      VARCHAR(100)    NOT NULL,
    middle_name    VARCHAR(100)    NULL,
    bu_email       VARCHAR(255)    NULL,
    contact        VARCHAR(50)     NULL,
    sex            CHAR(1)         NULL,
    year_level     SMALLINT NULL,
    status         TEXT NOT NULL DEFAULT 'active',
    admission_date DATE            NULL,
    birthdate      DATE            NULL,
    user_id        INTEGER    NULL,
    created_at     TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at     TIMESTAMP(6)     NULL DEFAULT NULL,
    PRIMARY KEY (student_id),
    CONSTRAINT uq_students_student_number UNIQUE (student_number),
    CONSTRAINT uq_students_user_id UNIQUE (user_id),
    CONSTRAINT fk_students_user FOREIGN KEY (user_id)
        REFERENCES user_accounts (user_id)
        ON DELETE SET NULL
        ON UPDATE RESTRICT
);


-- ---------------------------------------------------------------------------
-- 6. enrollments
-- One row = one student enrolled in one class-section (course offering).
-- Holds grade, retention state, and remedial state for that offering only.
-- FKs: students, class_sections.
-- ---------------------------------------------------------------------------
CREATE TABLE enrollments (
    enrollment_id     INTEGER GENERATED BY DEFAULT AS IDENTITY,
    student_id        INTEGER    NOT NULL,
    cs_id             INTEGER    NOT NULL,
    status            VARCHAR(20)     NOT NULL DEFAULT 'Active',
    date_enrolled     DATE            NULL,
    final_percentage  DECIMAL(5,2)    NULL,
    final_gwa         DECIMAL(4,2)    NULL,
    grade_components_JSONB JSONB NULL,
    retention_state   TEXT NOT NULL DEFAULT 'active',
    remedial_state_JSONB JSONB NULL,
    clinic_hours_completed INTEGER NOT NULL DEFAULT 0,
    created_at        TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at        TIMESTAMP(6)     NULL DEFAULT NULL,
    PRIMARY KEY (enrollment_id),
    CONSTRAINT uq_enrollments_student_cs UNIQUE (student_id, cs_id),
    CONSTRAINT fk_enrollments_student FOREIGN KEY (student_id)
        REFERENCES students (student_id)
        ON DELETE RESTRICT
        ON UPDATE RESTRICT,
    CONSTRAINT fk_enrollments_cs FOREIGN KEY (cs_id)
        REFERENCES class_sections (cs_id)
        ON DELETE RESTRICT
        ON UPDATE RESTRICT
);


-- ---------------------------------------------------------------------------
-- 7. assessments
-- Assessment/activity definitions for a class-section.
-- FK: class_sections.
-- ---------------------------------------------------------------------------
CREATE TABLE assessments (
    assessment_id  INTEGER GENERATED BY DEFAULT AS IDENTITY,
    cs_id          INTEGER    NOT NULL,
    title          VARCHAR(255)    NOT NULL,
    type           TEXT NOT NULL,
    grading_period TEXT NULL,
    max_score      DECIMAL(6,2)    NOT NULL,
    weight         DECIMAL(5,2)    NULL,
    due_date       DATE            NULL,
    instructions   TEXT            NULL,
    status         TEXT NOT NULL DEFAULT 'Active',
    created_at     TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at     TIMESTAMP(6)     NULL DEFAULT NULL,
    PRIMARY KEY (assessment_id),
    CONSTRAINT fk_assessments_cs FOREIGN KEY (cs_id)
        REFERENCES class_sections (cs_id)
        ON DELETE RESTRICT
        ON UPDATE RESTRICT
);


-- ---------------------------------------------------------------------------
-- 8. assessment_scores
-- Individual student scores for an assessment.
-- FKs: assessments, students.
-- ---------------------------------------------------------------------------
CREATE TABLE assessment_scores (
    score_id      INTEGER GENERATED BY DEFAULT AS IDENTITY,
    assessment_id INTEGER    NOT NULL,
    student_id    INTEGER    NOT NULL,
    score         DECIMAL(6,2)    NOT NULL,
    submitted_at  TIMESTAMP(6)     NULL,
    remarks       VARCHAR(500)    NULL,
    PRIMARY KEY (score_id),
    CONSTRAINT uq_assessment_scores UNIQUE (assessment_id, student_id),
    CONSTRAINT fk_scores_assessment FOREIGN KEY (assessment_id)
        REFERENCES assessments (assessment_id)
        ON DELETE RESTRICT
        ON UPDATE RESTRICT,
    CONSTRAINT fk_scores_student FOREIGN KEY (student_id)
        REFERENCES students (student_id)
        ON DELETE RESTRICT
        ON UPDATE RESTRICT
);


-- ---------------------------------------------------------------------------
-- 9. attendance_records
-- Per-student attendance for a session, with override fields.
-- FKs: enrollments (authoritative relationship), user_accounts.
-- ---------------------------------------------------------------------------
CREATE TABLE attendance_records (
    record_id           INTEGER GENERATED BY DEFAULT AS IDENTITY,
    enrollment_id       INTEGER    NOT NULL,
    session_date        DATE            NOT NULL,
    session_code        VARCHAR(100)    NULL,
    session_start       TIME            NULL,
    session_end         TIME            NULL,
    status              TEXT NOT NULL,
    verification_method VARCHAR(50)     NULL,
    device_id           VARCHAR(50)     NULL,
    secretary_user_id   INTEGER    NULL,
    override_reason     VARCHAR(500)    NULL,
    override_by_user_id INTEGER    NULL,
    override_at         TIMESTAMP(6)     NULL,
    time_recorded       TIMESTAMP(6)     NULL,
    created_at          TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (record_id),
    CONSTRAINT uq_attendance_enrollment_date_code UNIQUE (enrollment_id, session_date, session_code),
    CONSTRAINT fk_att_enrollment FOREIGN KEY (enrollment_id)
        REFERENCES enrollments (enrollment_id)
        ON DELETE RESTRICT
        ON UPDATE RESTRICT,
    CONSTRAINT fk_att_secretary FOREIGN KEY (secretary_user_id)
        REFERENCES user_accounts (user_id)
        ON DELETE SET NULL
        ON UPDATE RESTRICT,
    CONSTRAINT fk_att_override_by FOREIGN KEY (override_by_user_id)
        REFERENCES user_accounts (user_id)
        ON DELETE SET NULL
        ON UPDATE RESTRICT
);


-- ---------------------------------------------------------------------------
-- 10. biometric_profiles
-- One row per student.  Protected template/image references.
-- Consent status.  Revocation clears template and image references.
-- FKs: students, user_accounts.
-- ---------------------------------------------------------------------------
CREATE TABLE biometric_profiles (
    profile_id          INTEGER GENERATED BY DEFAULT AS IDENTITY,
    student_id          INTEGER    NOT NULL,
    consent_status      TEXT NOT NULL DEFAULT 'pending',
    face_enrolled       SMALLINT      NOT NULL DEFAULT 0,
    template_reference  VARCHAR(500)    NULL,
    image_references    JSONB NULL,
    enrolled_at         TIMESTAMP(6)     NULL,
    consent_responded_at TIMESTAMP(6)    NULL,
    revoked_at          TIMESTAMP(6)     NULL,
    revoked_by_user_id  INTEGER    NULL,
    recorded_by_user_id INTEGER    NULL,
    created_at          TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at          TIMESTAMP(6)     NULL DEFAULT NULL,
    PRIMARY KEY (profile_id),
    CONSTRAINT uq_biometric_profiles_student UNIQUE (student_id),
    CONSTRAINT fk_bio_student FOREIGN KEY (student_id)
        REFERENCES students (student_id)
        ON DELETE RESTRICT
        ON UPDATE RESTRICT,
    CONSTRAINT fk_bio_revoked_by FOREIGN KEY (revoked_by_user_id)
        REFERENCES user_accounts (user_id)
        ON DELETE SET NULL
        ON UPDATE RESTRICT,
    CONSTRAINT fk_bio_recorded_by FOREIGN KEY (recorded_by_user_id)
        REFERENCES user_accounts (user_id)
        ON DELETE SET NULL
        ON UPDATE RESTRICT
);

-- NOTE: Revocation clears template_reference and image_references in
-- application code; triggers are not used for the clearance to avoid
-- cross-row storage operations in constraint enforcement.


-- ---------------------------------------------------------------------------
-- 11. auth_sessions
-- Session identity and lifecycle only.
-- issued_token_version enables account-wide invalidation.
-- Refresh-token digests and lineage are stored in security_tokens.
-- FK: user_accounts.
-- ---------------------------------------------------------------------------
CREATE TABLE auth_sessions (
    session_id           INTEGER GENERATED BY DEFAULT AS IDENTITY,
    session_uuid         CHAR(36)        NOT NULL,
    user_id              INTEGER    NOT NULL,
    issued_token_version INTEGER    NOT NULL,
    ip_address           VARCHAR(45)     NULL,
    user_agent           VARCHAR(512)    NULL,
    device_id            VARCHAR(100)    NULL,
    last_seen_at         TIMESTAMP(6)     NULL,
    created_at           TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    expires_at           TIMESTAMP(6)     NOT NULL,
    revoked_at           TIMESTAMP(6)     NULL,
    revocation_reason    VARCHAR(500)    NULL,
    PRIMARY KEY (session_id),
    CONSTRAINT uq_auth_sessions_session_uuid UNIQUE (session_uuid),
    CONSTRAINT fk_session_user FOREIGN KEY (user_id)
        REFERENCES user_accounts (user_id)
        ON DELETE RESTRICT
        ON UPDATE RESTRICT
);


-- ---------------------------------------------------------------------------
-- 12. security_tokens
-- Universal token store with purpose discriminator.
-- Nullable columns accommodate purpose-specific shapes.
-- FKs: user_accounts (nullable), auth_sessions, self(parent), students, cs.
-- ---------------------------------------------------------------------------
CREATE TABLE security_tokens (
    token_id          INTEGER GENERATED BY DEFAULT AS IDENTITY,
    purpose           TEXT NOT NULL,
    user_id           INTEGER    NULL,
    session_id        INTEGER    NULL,
    related_student_id INTEGER   NULL,
    related_cs_id     INTEGER    NULL,
    token_digest      BYTEA      NULL,
    secret_hash       VARCHAR(255)    NULL,
    family_uuid       CHAR(36)        NULL,
    parent_token_id   INTEGER    NULL,
    issued_at         TIMESTAMP(6)     NULL,
    expires_at        TIMESTAMP(6)     NULL,
    used_at           TIMESTAMP(6)     NULL,
    revoked_at        TIMESTAMP(6)     NULL,
    revocation_reason VARCHAR(500)    NULL,
    ciphertext        BYTEA  NULL,
    nonce             BYTEA   NULL,
    auth_tag          BYTEA   NULL,
    enc_key_version   INTEGER    NULL DEFAULT 1,
    enc_algorithm     VARCHAR(20)     NULL DEFAULT 'AES-256-GCM',
    totp_algorithm    VARCHAR(10)     NULL,
    digit_count       SMALLINT NULL,
    period_seconds    INTEGER    NULL,
    mfa_status        VARCHAR(20)     NULL,
    mfa_verified_at   TIMESTAMP(6)     NULL,
    last_accepted_step BIGINT NULL,
    metadata_JSONB JSONB NULL,
    PRIMARY KEY (token_id),
    CONSTRAINT uq_security_tokens_token_digest UNIQUE (token_digest),
    CONSTRAINT uq_security_tokens_parent_token_id UNIQUE (parent_token_id),
    CONSTRAINT fk_stoken_user FOREIGN KEY (user_id)
        REFERENCES user_accounts (user_id)
        ON DELETE RESTRICT
        ON UPDATE RESTRICT,
    CONSTRAINT fk_stoken_session FOREIGN KEY (session_id)
        REFERENCES auth_sessions (session_id)
        ON DELETE RESTRICT
        ON UPDATE RESTRICT,
    CONSTRAINT fk_stoken_parent FOREIGN KEY (parent_token_id)
        REFERENCES security_tokens (token_id)
        ON DELETE RESTRICT
        ON UPDATE RESTRICT,
    CONSTRAINT fk_stoken_related_student FOREIGN KEY (related_student_id)
        REFERENCES students (student_id)
        ON DELETE RESTRICT
        ON UPDATE RESTRICT,
    CONSTRAINT fk_stoken_related_cs FOREIGN KEY (related_cs_id)
        REFERENCES class_sections (cs_id)
        ON DELETE RESTRICT
        ON UPDATE RESTRICT
);

-- NOTE: token_digest and parent_token_id are nullable UNIQUE constraints.
-- MariaDB permits multiple NULL values in a UNIQUE column.
-- Cross-row application invariants (one active MFA per user, one pending
-- secretary invitation per student+cs) are enforced in application code.


-- ---------------------------------------------------------------------------
-- 13. audit_events
-- Append-only, tamper-evident audit trail with HMAC-SHA-256 chaining.
-- BEFORE UPDATE / BEFORE DELETE triggers enforce immutability.
-- FKs: user_accounts (SET NULL), auth_sessions (SET NULL).
-- ---------------------------------------------------------------------------
CREATE TABLE audit_events (
    event_id              INTEGER GENERATED BY DEFAULT AS IDENTITY,
    event_uuid            CHAR(36)        NOT NULL,
    sequence_number       BIGINT NOT NULL,
    occurred_at           TIMESTAMP(6)     NOT NULL,
    actor_user_id         INTEGER    NULL,
    actor_username        VARCHAR(255)    NULL,
    actor_role            VARCHAR(50)     NULL,
    actor_display_name    VARCHAR(255)    NULL,
    session_id            INTEGER    NULL,
    module_code           VARCHAR(100)    NOT NULL,
    action_code           VARCHAR(100)    NOT NULL,
    event_status          TEXT NOT NULL,
    target_type           VARCHAR(100)    NULL,
    target_id             VARCHAR(255)    NULL,
    description           TEXT            NULL,
    reason                VARCHAR(500)    NULL,
    http_method           VARCHAR(10)     NULL,
    endpoint              VARCHAR(255)    NULL,
    request_id            VARCHAR(100)    NULL,
    correlation_id        VARCHAR(100)    NULL,
    operation_uuid        CHAR(36)        NULL,
    ip_address            VARCHAR(45)     NULL,
    user_agent            VARCHAR(512)    NULL,
    device_id             VARCHAR(100)    NULL,
    device_name           VARCHAR(255)    NULL,
    before_state_JSONB TEXT        NULL,
    after_state_JSONB TEXT        NULL,
    before_state_hash     BYTEA      NULL,
    after_state_hash      BYTEA      NULL,
    previous_event_mac    BYTEA      NOT NULL,
    event_mac             BYTEA      NOT NULL,
    mac_key_version       INTEGER    NOT NULL,
    canonical_schema_version INTEGER NOT NULL,
    PRIMARY KEY (event_id),
    CONSTRAINT uq_audit_events_event_uuid UNIQUE (event_uuid),
    CONSTRAINT uq_audit_events_sequence UNIQUE (sequence_number),
    CONSTRAINT fk_audit_actor FOREIGN KEY (actor_user_id)
        REFERENCES user_accounts (user_id)
        ON DELETE SET NULL
        ON UPDATE RESTRICT,
    CONSTRAINT fk_audit_session FOREIGN KEY (session_id)
        REFERENCES auth_sessions (session_id)
        ON DELETE SET NULL
        ON UPDATE RESTRICT
);

CREATE FUNCTION audit_events_immutable() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'audit_events is append-only; % is not permitted', TG_OP;
END;
$$;

CREATE TRIGGER trg_audit_events_no_update BEFORE UPDATE ON audit_events
FOR EACH ROW EXECUTE FUNCTION audit_events_immutable();

CREATE TRIGGER trg_audit_events_no_delete BEFORE DELETE ON audit_events
FOR EACH ROW EXECUTE FUNCTION audit_events_immutable();


-- ---------------------------------------------------------------------------
-- 14. email_outbox
-- Outgoing email queue with delivery status.
-- FK: user_accounts (SET NULL).
-- ---------------------------------------------------------------------------
CREATE TABLE email_outbox (
    email_id          INTEGER GENERATED BY DEFAULT AS IDENTITY,
    sender_user_id    INTEGER    NULL,
    recipient_email   VARCHAR(255)    NOT NULL,
    recipient_name    VARCHAR(255)    NULL,
    subject           VARCHAR(500)    NOT NULL,
    email_type        TEXT NOT NULL,
    message_body      TEXT            NULL,
    status            TEXT NOT NULL DEFAULT 'Pending',
    sent_at           TIMESTAMP(6)     NULL,
    failure_reason    TEXT            NULL,
    operation_uuid    CHAR(36)        NOT NULL,
    created_at        TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (email_id),
    CONSTRAINT uq_email_outbox_operation_uuid UNIQUE (operation_uuid),
    CONSTRAINT fk_email_sender FOREIGN KEY (sender_user_id)
        REFERENCES user_accounts (user_id)
        ON DELETE SET NULL
        ON UPDATE RESTRICT
);


-- ---------------------------------------------------------------------------
-- 15. system_settings
-- Global key-value configuration store.
-- is_internal marks rows reserved for system use (e.g., audit chain head).
-- FK: user_accounts (SET NULL).
-- ---------------------------------------------------------------------------
CREATE TABLE system_settings (
    setting_id        INTEGER GENERATED BY DEFAULT AS IDENTITY,
    setting_key       VARCHAR(100)    NOT NULL,
    setting_value     JSONB NOT NULL,
    is_internal       SMALLINT      NOT NULL DEFAULT 0,
    description       VARCHAR(500)    NULL,
    updated_at        TIMESTAMP(6)     NULL,
    updated_by_user_id INTEGER   NULL,
    PRIMARY KEY (setting_id),
    CONSTRAINT uq_system_settings_key UNIQUE (setting_key),
    CONSTRAINT fk_settings_updater FOREIGN KEY (updated_by_user_id)
        REFERENCES user_accounts (user_id)
        ON DELETE SET NULL
        ON UPDATE RESTRICT
);

CREATE FUNCTION system_settings_protect_internal() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP = 'DELETE' AND OLD.is_internal = 1 THEN
        RAISE EXCEPTION 'Internal system_settings rows cannot be deleted';
    END IF;
    IF TG_OP = 'UPDATE' AND OLD.is_internal = 1
       AND (NEW.setting_key <> OLD.setting_key OR NEW.is_internal <> 1) THEN
        RAISE EXCEPTION 'Internal system_settings identity is immutable';
    END IF;
    RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
END;
$$;

CREATE TRIGGER trg_system_settings_internal_no_delete BEFORE DELETE ON system_settings
FOR EACH ROW EXECUTE FUNCTION system_settings_protect_internal();

CREATE TRIGGER trg_system_settings_internal_identity_guard BEFORE UPDATE ON system_settings
FOR EACH ROW EXECUTE FUNCTION system_settings_protect_internal();

CREATE FUNCTION touch_updated_at() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at := CURRENT_TIMESTAMP(6);
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_user_accounts_updated_at BEFORE UPDATE ON user_accounts
FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
CREATE TRIGGER trg_enrollments_updated_at BEFORE UPDATE ON enrollments
FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
CREATE TRIGGER trg_assessments_updated_at BEFORE UPDATE ON assessments
FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

ALTER TABLE user_accounts ADD CONSTRAINT ck_user_accounts_role CHECK (role IN ('admin','faculty','secretary'));
ALTER TABLE user_accounts ADD CONSTRAINT ck_user_accounts_theme CHECK (theme IN ('light','dark'));
ALTER TABLE role_permissions ADD CONSTRAINT ck_role_permissions_role CHECK (role_name IN ('admin','faculty','secretary'));
ALTER TABLE role_permissions ADD CONSTRAINT ck_role_permissions_scope CHECK (scope IN ('own','assigned_class','assigned_course','aggregate','system_wide'));
ALTER TABLE courses ADD CONSTRAINT ck_courses_semester CHECK (semester IS NULL OR semester IN ('1ST','2ND','Summer'));
ALTER TABLE students ADD CONSTRAINT ck_students_status CHECK (status IN ('active','disabled','archived'));
ALTER TABLE enrollments ADD CONSTRAINT ck_enrollments_retention CHECK (retention_state IN ('active','warning','critical','remedial','archived'));
ALTER TABLE assessments ADD CONSTRAINT ck_assessments_status CHECK (status IN ('Active','Closed','Archived'));
ALTER TABLE attendance_records ADD CONSTRAINT ck_attendance_status CHECK (status IN ('present','absent','late','excused'));
ALTER TABLE biometric_profiles ADD CONSTRAINT ck_biometric_consent CHECK (consent_status IN ('pending','approved','declined'));
ALTER TABLE security_tokens ADD CONSTRAINT ck_security_tokens_purpose CHECK (purpose IN ('mfa_credential','mfa_recovery','password_reset','access_token_blacklist','secretary_invitation','refresh'));
ALTER TABLE audit_events ADD CONSTRAINT ck_audit_status CHECK (event_status IN ('Success','Failed','Warning'));
ALTER TABLE email_outbox ADD CONSTRAINT ck_email_status CHECK (status IN ('Pending','Sent','Failed'));
ALTER TABLE system_settings ADD CONSTRAINT ck_settings_internal CHECK (is_internal IN (0,1));
ALTER TABLE audit_events ADD CONSTRAINT ck_audit_previous_mac_length CHECK (octet_length(previous_event_mac) = 32);
ALTER TABLE audit_events ADD CONSTRAINT ck_audit_event_mac_length CHECK (octet_length(event_mac) = 32);
ALTER TABLE user_accounts ALTER COLUMN login_email TYPE CITEXT;
ALTER TABLE students ALTER COLUMN bu_email TYPE CITEXT;
ALTER TABLE email_outbox ALTER COLUMN recipient_email TYPE CITEXT;

CREATE INDEX idx_user_accounts_role ON user_accounts (role);
CREATE INDEX idx_user_accounts_status ON user_accounts (status);
CREATE INDEX idx_role_permissions_role_name ON role_permissions (role_name);
CREATE INDEX idx_courses_year_level ON courses (year_level);
CREATE INDEX idx_enrollments_student ON enrollments (student_id);
CREATE INDEX idx_enrollments_cs ON enrollments (cs_id);
CREATE INDEX idx_assessments_cs ON assessments (cs_id);
CREATE INDEX idx_assessment_scores_assessment ON assessment_scores (assessment_id);
CREATE INDEX idx_attendance_enrollment ON attendance_records (enrollment_id);
CREATE INDEX idx_stoken_user_purpose ON security_tokens (user_id, purpose);
CREATE INDEX idx_stoken_session ON security_tokens (session_id);
CREATE INDEX idx_stoken_family ON security_tokens (family_uuid);
CREATE INDEX idx_audit_events_occurred_at ON audit_events (occurred_at);
CREATE INDEX idx_audit_events_actor ON audit_events (actor_user_id);
CREATE INDEX idx_audit_events_module ON audit_events (module_code);
CREATE INDEX idx_email_outbox_status ON email_outbox (status);
