-- Persistent attendance-session lifecycle for authorized Secretary workflows.
-- Historical attendance rows remain valid through a nullable session reference.

CREATE TABLE IF NOT EXISTS attendance_sessions (
    session_id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cs_id                     INTEGER NOT NULL,
    secretary_user_id         INTEGER NOT NULL,
    session_date              DATE NOT NULL,
    session_code              VARCHAR(100) NOT NULL,
    room                      VARCHAR(255) NULL,
    started_at                TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    ended_at                  TIMESTAMP(6) WITHOUT TIME ZONE NULL,
    status                    TEXT NOT NULL DEFAULT 'active',
    geofence_enabled          BOOLEAN NOT NULL DEFAULT FALSE,
    geofence_latitude         NUMERIC(9, 6) NULL,
    geofence_longitude        NUMERIC(9, 6) NULL,
    geofence_radius_meters    NUMERIC(8, 2) NULL,
    biometric_required        BOOLEAN NOT NULL DEFAULT FALSE,
    created_at                TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at                TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP(6),

    CONSTRAINT fk_attendance_sessions_cs
        FOREIGN KEY (cs_id)
        REFERENCES class_sections (cs_id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,
    CONSTRAINT fk_attendance_sessions_secretary
        FOREIGN KEY (secretary_user_id)
        REFERENCES user_accounts (user_id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,
    CONSTRAINT ck_attendance_sessions_status
        CHECK (status IN ('active', 'ended')),
    CONSTRAINT ck_attendance_sessions_lifecycle
        CHECK (
            (status = 'active' AND ended_at IS NULL)
            OR (status = 'ended' AND ended_at IS NOT NULL)
        ),
    CONSTRAINT ck_attendance_sessions_geofence_coordinates
        CHECK (
            (geofence_latitude IS NULL AND geofence_longitude IS NULL)
            OR (geofence_latitude BETWEEN -90 AND 90 AND geofence_longitude BETWEEN -180 AND 180)
        ),
    CONSTRAINT ck_attendance_sessions_geofence_radius
        CHECK (geofence_radius_meters IS NULL OR geofence_radius_meters > 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_attendance_sessions_active_section
    ON attendance_sessions (cs_id)
    WHERE status = 'active';

CREATE UNIQUE INDEX IF NOT EXISTS uq_attendance_sessions_section_date_code
    ON attendance_sessions (cs_id, session_date, session_code);

CREATE INDEX IF NOT EXISTS idx_attendance_sessions_secretary_status
    ON attendance_sessions (secretary_user_id, status, session_date DESC);

ALTER TABLE attendance_records
    ADD COLUMN IF NOT EXISTS attendance_session_id INTEGER NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_attendance_records_session'
          AND conrelid = 'attendance_records'::regclass
    ) THEN
        ALTER TABLE attendance_records
            ADD CONSTRAINT fk_attendance_records_session
            FOREIGN KEY (attendance_session_id)
            REFERENCES attendance_sessions (session_id)
            ON UPDATE RESTRICT
            ON DELETE RESTRICT;
    END IF;
END
$$;

CREATE INDEX IF NOT EXISTS idx_attendance_records_session
    ON attendance_records (attendance_session_id);
