-- Authoritative Faculty/course/term/school-year grading configurations.
-- Legacy courses.grading_config and assessments.type remain available for
-- compatibility until an authoritative configuration is saved.

CREATE TABLE grading_configs (
    config_id          INTEGER GENERATED BY DEFAULT AS IDENTITY,
    faculty_user_id    INTEGER NOT NULL,
    course_id          INTEGER NOT NULL,
    semester           TEXT NOT NULL,
    school_year        VARCHAR(20) NOT NULL,
    version            INTEGER NOT NULL DEFAULT 1,
    created_at         TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at         TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_by_user_id INTEGER NULL,
    PRIMARY KEY (config_id),
    CONSTRAINT uq_grading_configs_offering
        UNIQUE (faculty_user_id, course_id, semester, school_year),
    CONSTRAINT ck_grading_configs_semester_nonblank
        CHECK (btrim(semester) <> ''),
    CONSTRAINT ck_grading_configs_school_year_nonblank
        CHECK (btrim(school_year) <> ''),
    CONSTRAINT ck_grading_configs_version_positive
        CHECK (version > 0),
    CONSTRAINT fk_grading_configs_faculty FOREIGN KEY (faculty_user_id)
        REFERENCES user_accounts (user_id)
        ON DELETE RESTRICT
        ON UPDATE RESTRICT,
    CONSTRAINT fk_grading_configs_course FOREIGN KEY (course_id)
        REFERENCES courses (course_id)
        ON DELETE RESTRICT
        ON UPDATE RESTRICT,
    CONSTRAINT fk_grading_configs_updater FOREIGN KEY (updated_by_user_id)
        REFERENCES user_accounts (user_id)
        ON DELETE SET NULL
        ON UPDATE RESTRICT
);

CREATE TABLE grading_categories (
    category_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    config_id   INTEGER NOT NULL,
    name        VARCHAR(255) NOT NULL,
    weight      DECIMAL(7,4) NOT NULL,
    sort_order  INTEGER NOT NULL,
    created_at  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (category_id),
    CONSTRAINT ck_grading_categories_name_nonblank
        CHECK (btrim(name) <> ''),
    CONSTRAINT ck_grading_categories_weight_positive
        CHECK (weight > 0 AND weight <= 100),
    CONSTRAINT ck_grading_categories_sort_order_positive
        CHECK (sort_order > 0),
    CONSTRAINT fk_grading_categories_config FOREIGN KEY (config_id)
        REFERENCES grading_configs (config_id)
        ON DELETE CASCADE
        ON UPDATE RESTRICT
);

CREATE UNIQUE INDEX uq_grading_categories_config_name
    ON grading_categories (config_id, lower(btrim(name)));

ALTER TABLE assessments
    ADD COLUMN grading_category_id INTEGER NULL;

ALTER TABLE assessments
    ADD CONSTRAINT fk_assessments_grading_category
    FOREIGN KEY (grading_category_id)
    REFERENCES grading_categories (category_id)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT;

CREATE INDEX idx_assessments_grading_category
    ON assessments (grading_category_id);

CREATE TRIGGER trg_grading_configs_updated_at
BEFORE UPDATE ON grading_configs
FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

CREATE TRIGGER trg_grading_categories_updated_at
BEFORE UPDATE ON grading_categories
FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
