-- Store period-specific category definitions without changing the stable
-- category IDs referenced by assessments and scores.

CREATE TABLE grading_category_periods (
    category_period_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_id BIGINT NOT NULL REFERENCES grading_configs(config_id) ON DELETE CASCADE,
    category_id BIGINT NOT NULL REFERENCES grading_categories(category_id) ON DELETE RESTRICT,
    grading_period TEXT NOT NULL,
    name VARCHAR(255) NOT NULL,
    weight NUMERIC(7,4) NOT NULL,
    sort_order INTEGER NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT ck_grading_category_periods_period
        CHECK (grading_period IN ('Midterm', 'Final')),
    CONSTRAINT ck_grading_category_periods_name
        CHECK (btrim(name) <> ''),
    CONSTRAINT ck_grading_category_periods_weight
        CHECK (weight > 0 AND weight <= 100),
    CONSTRAINT ck_grading_category_periods_sort_order
        CHECK (sort_order > 0),
    CONSTRAINT uq_grading_category_periods_category
        UNIQUE (config_id, category_id, grading_period)
);

CREATE UNIQUE INDEX uq_grading_category_periods_name
    ON grading_category_periods (config_id, grading_period, lower(btrim(name)));

CREATE INDEX ix_grading_category_periods_config_period
    ON grading_category_periods (config_id, grading_period, sort_order, category_period_id);
