-- Additive, recipient-scoped notifications for persisted academic events.
-- Notification delivery is intentionally independent from email delivery.

CREATE TABLE IF NOT EXISTS notifications (
    notification_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_user_id    INTEGER NOT NULL,
    notification_type    VARCHAR(100) NOT NULL,
    title                VARCHAR(255) NOT NULL,
    body                 TEXT NOT NULL,
    entity_type          VARCHAR(100) NULL,
    entity_id            VARCHAR(100) NULL,
    deduplication_key    VARCHAR(255) NULL,
    read_at              TIMESTAMP(6) WITHOUT TIME ZONE NULL,
    created_at           TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP(6),

    CONSTRAINT fk_notifications_recipient
        FOREIGN KEY (recipient_user_id)
        REFERENCES user_accounts (user_id)
        ON UPDATE RESTRICT
        ON DELETE CASCADE,
    CONSTRAINT ck_notifications_type_nonblank
        CHECK (btrim(notification_type) <> ''),
    CONSTRAINT ck_notifications_title_nonblank
        CHECK (btrim(title) <> ''),
    CONSTRAINT ck_notifications_body_nonblank
        CHECK (btrim(body) <> ''),
    CONSTRAINT ck_notifications_dedupe_nonblank
        CHECK (deduplication_key IS NULL OR btrim(deduplication_key) <> '')
);

CREATE INDEX IF NOT EXISTS idx_notifications_recipient_created
    ON notifications (recipient_user_id, created_at DESC, notification_id DESC);

CREATE INDEX IF NOT EXISTS idx_notifications_recipient_unread
    ON notifications (recipient_user_id, notification_id)
    WHERE read_at IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_notifications_recipient_dedupe
    ON notifications (recipient_user_id, deduplication_key)
    WHERE deduplication_key IS NOT NULL;
