-- Additive 3NF support for canonical identity and repeated academic facts.
-- Legacy JSON and session snapshot columns remain during the compatibility
-- period. They are compatibility caches; the normalized relations below are
-- the controlled relational representation of the current facts.

CREATE TABLE IF NOT EXISTS person_identities (
    person_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_prefix         VARCHAR(50) NULL,
    first_name          VARCHAR(100) NULL,
    middle_name         VARCHAR(100) NULL,
    last_name           VARCHAR(100) NULL,
    name_suffix         VARCHAR(50) NULL,
    legacy_display_name VARCHAR(255) NULL,
    created_at          TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at          TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
);

ALTER TABLE user_accounts
    ADD COLUMN IF NOT EXISTS person_id BIGINT NULL;

ALTER TABLE students
    ADD COLUMN IF NOT EXISTS person_id BIGINT NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_user_accounts_person'
          AND conrelid = 'user_accounts'::regclass
    ) THEN
        ALTER TABLE user_accounts
            ADD CONSTRAINT fk_user_accounts_person
            FOREIGN KEY (person_id) REFERENCES person_identities(person_id)
            ON UPDATE RESTRICT ON DELETE RESTRICT;
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_students_person'
          AND conrelid = 'students'::regclass
    ) THEN
        ALTER TABLE students
            ADD CONSTRAINT fk_students_person
            FOREIGN KEY (person_id) REFERENCES person_identities(person_id)
            ON UPDATE RESTRICT ON DELETE RESTRICT;
    END IF;
END
$$;

CREATE UNIQUE INDEX IF NOT EXISTS uq_user_accounts_person
    ON user_accounts (person_id)
    WHERE person_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_students_person
    ON students (person_id)
    WHERE person_id IS NOT NULL;

-- Populate one canonical identity per account, then attach linked Students to
-- the same identity. Legacy display names are retained without guessing a
-- first/last split.
DO $$
DECLARE
    account_row RECORD;
    student_row RECORD;
    linked_person BIGINT;
BEGIN
    FOR account_row IN
        SELECT user_id, display_name, name_prefix, first_name, middle_name, last_name, name_suffix
        FROM user_accounts
        WHERE person_id IS NULL
    LOOP
        INSERT INTO person_identities (
            name_prefix, first_name, middle_name, last_name, name_suffix, legacy_display_name
        ) VALUES (
            account_row.name_prefix, account_row.first_name, account_row.middle_name,
            account_row.last_name, account_row.name_suffix, account_row.display_name
        ) RETURNING person_id INTO linked_person;

        UPDATE user_accounts
           SET person_id = linked_person
         WHERE user_id = account_row.user_id;
    END LOOP;

    FOR student_row IN
        SELECT student_id, user_id, student_account_user_id, name_prefix, first_name,
               middle_name, last_name, name_suffix
        FROM students
        WHERE person_id IS NULL
    LOOP
        linked_person := NULL;
        SELECT ua.person_id
          INTO linked_person
          FROM user_accounts ua
         WHERE ua.user_id = COALESCE(student_row.student_account_user_id, student_row.user_id)
           AND ua.person_id IS NOT NULL;

        IF linked_person IS NULL THEN
            INSERT INTO person_identities (
                name_prefix, first_name, middle_name, last_name, name_suffix
            ) VALUES (
                student_row.name_prefix, student_row.first_name, student_row.middle_name,
                student_row.last_name, student_row.name_suffix
            ) RETURNING person_id INTO linked_person;
        ELSE
            -- Student names are already structured and therefore may enrich an
            -- older ambiguous account display name without parsing it.
            UPDATE person_identities
               SET name_prefix = COALESCE(name_prefix, student_row.name_prefix),
                   first_name = COALESCE(first_name, student_row.first_name),
                   middle_name = COALESCE(middle_name, student_row.middle_name),
                   last_name = COALESCE(last_name, student_row.last_name),
                   name_suffix = COALESCE(name_suffix, student_row.name_suffix),
                   updated_at = CURRENT_TIMESTAMP(6)
             WHERE person_id = linked_person;
        END IF;

        UPDATE students
           SET person_id = linked_person
         WHERE student_id = student_row.student_id;
    END LOOP;
END
$$;

CREATE OR REPLACE FUNCTION sync_user_account_person_identity()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.person_id IS NULL THEN
        INSERT INTO person_identities (
            name_prefix, first_name, middle_name, last_name, name_suffix, legacy_display_name
        ) VALUES (
            NEW.name_prefix, NEW.first_name, NEW.middle_name, NEW.last_name,
            NEW.name_suffix, NEW.display_name
        ) RETURNING person_id INTO NEW.person_id;
    ELSE
        UPDATE person_identities
           SET name_prefix = NEW.name_prefix,
               first_name = NEW.first_name,
               middle_name = NEW.middle_name,
               last_name = NEW.last_name,
               name_suffix = NEW.name_suffix,
               legacy_display_name = NEW.display_name,
               updated_at = CURRENT_TIMESTAMP(6)
         WHERE person_id = NEW.person_id;
    END IF;
    RETURN NEW;
END
$$;

DROP TRIGGER IF EXISTS trg_user_accounts_person_identity ON user_accounts;
CREATE TRIGGER trg_user_accounts_person_identity
BEFORE INSERT OR UPDATE OF display_name, name_prefix, first_name, middle_name, last_name, name_suffix, person_id
ON user_accounts
FOR EACH ROW EXECUTE FUNCTION sync_user_account_person_identity();

CREATE OR REPLACE FUNCTION sync_student_person_identity()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    account_person BIGINT;
BEGIN
    SELECT person_id
      INTO account_person
      FROM user_accounts
     WHERE user_id = COALESCE(NEW.student_account_user_id, NEW.user_id)
       AND person_id IS NOT NULL;

    IF account_person IS NOT NULL THEN
        NEW.person_id := account_person;
    ELSIF NEW.person_id IS NULL THEN
        INSERT INTO person_identities (
            name_prefix, first_name, middle_name, last_name, name_suffix
        ) VALUES (
            NEW.name_prefix, NEW.first_name, NEW.middle_name, NEW.last_name, NEW.name_suffix
        ) RETURNING person_id INTO NEW.person_id;
    END IF;

    UPDATE person_identities
       SET name_prefix = NEW.name_prefix,
           first_name = NEW.first_name,
           middle_name = NEW.middle_name,
           last_name = NEW.last_name,
           name_suffix = NEW.name_suffix,
           updated_at = CURRENT_TIMESTAMP(6)
     WHERE person_id = NEW.person_id;
    RETURN NEW;
END
$$;

DROP TRIGGER IF EXISTS trg_students_person_identity ON students;
CREATE TRIGGER trg_students_person_identity
BEFORE INSERT OR UPDATE OF user_id, student_account_user_id, name_prefix, first_name, middle_name, last_name, name_suffix, person_id
ON students
FOR EACH ROW EXECUTE FUNCTION sync_student_person_identity();

-- A period membership's category determines its configuration. Keep the old
-- config_id/name/weight columns for existing API consumers, but maintain a
-- canonical relation whose determinant is category_id plus grading_period.
CREATE TABLE IF NOT EXISTS grading_category_period_memberships (
    category_period_id BIGINT PRIMARY KEY REFERENCES grading_category_periods(category_period_id)
        ON UPDATE RESTRICT ON DELETE CASCADE,
    category_id BIGINT NOT NULL REFERENCES grading_categories(category_id)
        ON UPDATE RESTRICT ON DELETE CASCADE,
    grading_period TEXT NOT NULL,
    name VARCHAR(255) NOT NULL,
    weight NUMERIC(7,4) NOT NULL,
    sort_order INTEGER NOT NULL,
    source_kind TEXT NOT NULL DEFAULT 'assessment',
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT ck_gcpm_period CHECK (grading_period IN ('Midterm', 'Final')),
    CONSTRAINT ck_gcpm_name CHECK (btrim(name) <> ''),
    CONSTRAINT ck_gcpm_weight CHECK (weight > 0 AND weight <= 100),
    CONSTRAINT ck_gcpm_sort_order CHECK (sort_order > 0),
    CONSTRAINT ck_gcpm_source_kind CHECK (source_kind IN ('attendance', 'assessment')),
    CONSTRAINT uq_gcpm_category_period UNIQUE (category_id, grading_period)
);

INSERT INTO grading_category_period_memberships (
    category_period_id, category_id, grading_period, name, weight, sort_order, source_kind,
    created_at, updated_at
)
SELECT category_period_id, category_id, grading_period, name, weight, sort_order, source_kind,
       created_at, updated_at
  FROM grading_category_periods
ON CONFLICT (category_period_id) DO UPDATE SET
    category_id = EXCLUDED.category_id,
    grading_period = EXCLUDED.grading_period,
    name = EXCLUDED.name,
    weight = EXCLUDED.weight,
    sort_order = EXCLUDED.sort_order,
    source_kind = EXCLUDED.source_kind,
    updated_at = EXCLUDED.updated_at;

CREATE OR REPLACE FUNCTION sync_grading_category_period_membership()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        DELETE FROM grading_category_period_memberships
         WHERE category_period_id = OLD.category_period_id;
        RETURN OLD;
    END IF;

    INSERT INTO grading_category_period_memberships (
        category_period_id, category_id, grading_period, name, weight, sort_order, source_kind,
        created_at, updated_at
    ) VALUES (
        NEW.category_period_id, NEW.category_id, NEW.grading_period, NEW.name, NEW.weight,
        NEW.sort_order, NEW.source_kind, NEW.created_at, NEW.updated_at
    )
    ON CONFLICT (category_period_id) DO UPDATE SET
        category_id = EXCLUDED.category_id,
        grading_period = EXCLUDED.grading_period,
        name = EXCLUDED.name,
        weight = EXCLUDED.weight,
        sort_order = EXCLUDED.sort_order,
        source_kind = EXCLUDED.source_kind,
        updated_at = EXCLUDED.updated_at;
    RETURN NEW;
END
$$;

DROP TRIGGER IF EXISTS trg_grading_category_period_membership ON grading_category_periods;
CREATE TRIGGER trg_grading_category_period_membership
AFTER INSERT OR UPDATE OR DELETE ON grading_category_periods
FOR EACH ROW EXECUTE FUNCTION sync_grading_category_period_membership();

CREATE TABLE IF NOT EXISTS enrollment_grade_breakdowns (
    enrollment_id       INTEGER PRIMARY KEY REFERENCES enrollments(enrollment_id)
        ON UPDATE RESTRICT ON DELETE CASCADE,
    calculation_mode    TEXT NULL,
    final_percentage    NUMERIC(5,2) NULL,
    final_gwa           NUMERIC(4,2) NULL,
    retention_state     TEXT NOT NULL,
    retention_threshold NUMERIC(4,2) NULL,
    recorded_at         TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT ck_egb_percentage CHECK (final_percentage IS NULL OR (final_percentage >= 0 AND final_percentage <= 100)),
    CONSTRAINT ck_egb_gwa CHECK (final_gwa IS NULL OR (final_gwa >= 0 AND final_gwa <= 5)),
    CONSTRAINT ck_egb_retention CHECK (retention_state IN ('active', 'warning', 'critical', 'remedial', 'archived'))
);

CREATE TABLE IF NOT EXISTS enrollment_grade_breakdown_categories (
    enrollment_id   INTEGER NOT NULL REFERENCES enrollment_grade_breakdowns(enrollment_id)
        ON UPDATE RESTRICT ON DELETE CASCADE,
    grading_period  TEXT NOT NULL,
    category_key    VARCHAR(255) NOT NULL,
    category_id     BIGINT NULL REFERENCES grading_categories(category_id)
        ON UPDATE RESTRICT ON DELETE CASCADE,
    category_name   VARCHAR(255) NULL,
    earned_points   NUMERIC(12,4) NULL,
    possible_points NUMERIC(12,4) NULL,
    ratio           NUMERIC(12,8) NULL,
    weight          NUMERIC(7,4) NULL,
    contribution    NUMERIC(12,4) NULL,
    PRIMARY KEY (enrollment_id, grading_period, category_key),
    CONSTRAINT ck_egbc_period CHECK (grading_period IN ('overall', 'Midterm', 'Final'))
);

CREATE OR REPLACE FUNCTION normalization_jsonb_number(value JSONB)
RETURNS NUMERIC
LANGUAGE plpgsql
IMMUTABLE
AS $$
DECLARE
    raw_value TEXT;
BEGIN
    IF value IS NULL OR jsonb_typeof(value) NOT IN ('number', 'string') THEN
        RETURN NULL;
    END IF;
    raw_value := NULLIF(btrim(value #>> '{}'), '');
    IF raw_value IS NULL OR raw_value !~ '^-?[0-9]+(\\.[0-9]+)?$' THEN
        RETURN NULL;
    END IF;
    RETURN raw_value::NUMERIC;
END
$$;

CREATE OR REPLACE FUNCTION refresh_enrollment_grade_breakdown(
    target_enrollment_id INTEGER,
    components JSONB,
    target_percentage NUMERIC,
    target_gwa NUMERIC,
    target_retention_state TEXT,
    target_recorded_at TIMESTAMP(6)
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
DECLARE
    category JSONB;
    category_index INTEGER;
    period_name TEXT;
    category_list JSONB;
    category_key_value TEXT;
BEGIN
    INSERT INTO enrollment_grade_breakdowns (
        enrollment_id, calculation_mode, final_percentage, final_gwa, retention_state,
        retention_threshold, recorded_at
    ) VALUES (
        target_enrollment_id,
        CASE WHEN components IS NULL THEN NULL ELSE components->>'calculationMode' END,
        target_percentage,
        target_gwa,
        target_retention_state,
        normalization_jsonb_number(CASE WHEN components IS NULL THEN NULL ELSE components->'retentionThreshold' END),
        COALESCE(target_recorded_at, CURRENT_TIMESTAMP(6))
    )
    ON CONFLICT (enrollment_id) DO UPDATE SET
        calculation_mode = EXCLUDED.calculation_mode,
        final_percentage = EXCLUDED.final_percentage,
        final_gwa = EXCLUDED.final_gwa,
        retention_state = EXCLUDED.retention_state,
        retention_threshold = EXCLUDED.retention_threshold,
        recorded_at = EXCLUDED.recorded_at;

    DELETE FROM enrollment_grade_breakdown_categories
     WHERE enrollment_id = target_enrollment_id;

    IF components IS NULL THEN
        RETURN;
    END IF;

    FOREACH period_name IN ARRAY ARRAY['overall', 'Midterm', 'Final'] LOOP
        category_list := CASE
            WHEN period_name = 'overall' THEN components->'categories'
            WHEN period_name = 'Midterm' THEN components->'periods'->'midterm'->'categories'
            ELSE components->'periods'->'final'->'categories'
        END;
        IF category_list IS NULL OR jsonb_typeof(category_list) <> 'array' THEN
            CONTINUE;
        END IF;

        category_index := 0;
        FOR category IN SELECT value FROM jsonb_array_elements(category_list) LOOP
            category_index := category_index + 1;
            category_key_value := COALESCE(
                NULLIF(category->>'categoryId', ''),
                NULLIF(category->>'name', ''),
                'category-' || category_index::TEXT
            );
            INSERT INTO enrollment_grade_breakdown_categories (
                enrollment_id, grading_period, category_key, category_id, category_name,
                earned_points, possible_points, ratio, weight, contribution
            ) VALUES (
                target_enrollment_id,
                period_name,
                category_key_value,
                CASE
                    WHEN category->>'categoryId' ~ '^[0-9]+$'
                     AND EXISTS (
                         SELECT 1 FROM grading_categories
                          WHERE category_id = (category->>'categoryId')::BIGINT
                     )
                    THEN (category->>'categoryId')::BIGINT
                    ELSE NULL
                END,
                NULLIF(category->>'name', ''),
                normalization_jsonb_number(category->'earnedPoints'),
                normalization_jsonb_number(category->'possiblePoints'),
                normalization_jsonb_number(category->'ratio'),
                normalization_jsonb_number(category->'weight'),
                normalization_jsonb_number(category->'contribution')
            )
            ON CONFLICT (enrollment_id, grading_period, category_key) DO UPDATE SET
                category_id = EXCLUDED.category_id,
                category_name = EXCLUDED.category_name,
                earned_points = EXCLUDED.earned_points,
                possible_points = EXCLUDED.possible_points,
                ratio = EXCLUDED.ratio,
                weight = EXCLUDED.weight,
                contribution = EXCLUDED.contribution;
        END LOOP;
    END LOOP;
END
$$;

CREATE OR REPLACE FUNCTION sync_enrollment_grade_breakdown()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM refresh_enrollment_grade_breakdown(
        NEW.enrollment_id, NEW.grade_components_json, NEW.final_percentage, NEW.final_gwa,
        NEW.retention_state, NEW.updated_at
    );
    RETURN NEW;
END
$$;

DROP TRIGGER IF EXISTS trg_enrollment_grade_breakdown ON enrollments;
CREATE TRIGGER trg_enrollment_grade_breakdown
AFTER INSERT OR UPDATE OF grade_components_json, final_percentage, final_gwa, retention_state
ON enrollments
FOR EACH ROW EXECUTE FUNCTION sync_enrollment_grade_breakdown();

INSERT INTO enrollment_grade_breakdowns (
    enrollment_id, calculation_mode, final_percentage, final_gwa, retention_state,
    retention_threshold, recorded_at
)
SELECT e.enrollment_id,
       e.grade_components_json->>'calculationMode',
       e.final_percentage,
       e.final_gwa,
       e.retention_state,
       normalization_jsonb_number(e.grade_components_json->'retentionThreshold'),
       COALESCE(e.updated_at, e.created_at, CURRENT_TIMESTAMP(6))
  FROM enrollments e
 WHERE e.grade_components_json IS NOT NULL
    OR e.final_percentage IS NOT NULL
    OR e.final_gwa IS NOT NULL
ON CONFLICT (enrollment_id) DO UPDATE SET
    calculation_mode = EXCLUDED.calculation_mode,
    final_percentage = EXCLUDED.final_percentage,
    final_gwa = EXCLUDED.final_gwa,
    retention_state = EXCLUDED.retention_state,
    retention_threshold = EXCLUDED.retention_threshold,
    recorded_at = EXCLUDED.recorded_at;

DO $$
DECLARE
    enrollment_row RECORD;
BEGIN
    FOR enrollment_row IN
        SELECT enrollment_id, grade_components_json, final_percentage, final_gwa,
               retention_state,
               COALESCE(updated_at, created_at, CURRENT_TIMESTAMP(6))::TIMESTAMP(6) AS recorded_at
        FROM enrollments
        WHERE grade_components_json IS NOT NULL
           OR final_percentage IS NOT NULL
           OR final_gwa IS NOT NULL
    LOOP
        PERFORM refresh_enrollment_grade_breakdown(
            enrollment_row.enrollment_id, enrollment_row.grade_components_json,
            enrollment_row.final_percentage, enrollment_row.final_gwa,
            enrollment_row.retention_state, enrollment_row.recorded_at
        );
    END LOOP;
END
$$;

CREATE TABLE IF NOT EXISTS enrollment_remedial_states (
    enrollment_id  INTEGER PRIMARY KEY REFERENCES enrollments(enrollment_id)
        ON UPDATE RESTRICT ON DELETE CASCADE,
    status         TEXT NULL,
    original_grade NUMERIC(4,2) NULL,
    remedial_score NUMERIC(5,2) NULL,
    remedial_grade NUMERIC(4,2) NULL,
    exam_date      DATE NULL,
    notes          TEXT NULL,
    updated_at     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT ck_ers_status CHECK (status IS NULL OR status IN ('pending', 'passed', 'failed', 'unavailable')),
    CONSTRAINT ck_ers_score CHECK (remedial_score IS NULL OR (remedial_score >= 0 AND remedial_score <= 100))
);

CREATE OR REPLACE FUNCTION refresh_enrollment_remedial_state(
    target_enrollment_id INTEGER,
    remedial JSONB,
    target_updated_at TIMESTAMP(6)
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
DECLARE
    exam_date_text TEXT;
BEGIN
    IF remedial IS NULL THEN
        DELETE FROM enrollment_remedial_states WHERE enrollment_id = target_enrollment_id;
        RETURN;
    END IF;

    exam_date_text := COALESCE(NULLIF(remedial->>'examDate', ''), NULLIF(remedial->>'dueDate', ''));
    INSERT INTO enrollment_remedial_states (
        enrollment_id, status, original_grade, remedial_score, remedial_grade,
        exam_date, notes, updated_at
    ) VALUES (
        target_enrollment_id,
        CASE WHEN remedial->>'status' IN ('pending', 'passed', 'failed', 'unavailable') THEN remedial->>'status' ELSE 'unavailable' END,
        normalization_jsonb_number(remedial->'originalGrade'),
        normalization_jsonb_number(remedial->'remedialScore'),
        normalization_jsonb_number(remedial->'remedialGrade'),
        CASE WHEN exam_date_text ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$' THEN exam_date_text::DATE ELSE NULL END,
        NULLIF(remedial->>'notes', ''),
        COALESCE(target_updated_at, CURRENT_TIMESTAMP(6))
    )
    ON CONFLICT (enrollment_id) DO UPDATE SET
        status = EXCLUDED.status,
        original_grade = EXCLUDED.original_grade,
        remedial_score = EXCLUDED.remedial_score,
        remedial_grade = EXCLUDED.remedial_grade,
        exam_date = EXCLUDED.exam_date,
        notes = EXCLUDED.notes,
        updated_at = EXCLUDED.updated_at;
END
$$;

CREATE OR REPLACE FUNCTION sync_enrollment_remedial_state()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM refresh_enrollment_remedial_state(NEW.enrollment_id, NEW.remedial_state_json, NEW.updated_at);
    RETURN NEW;
END
$$;

DROP TRIGGER IF EXISTS trg_enrollment_remedial_state ON enrollments;
CREATE TRIGGER trg_enrollment_remedial_state
AFTER INSERT OR UPDATE OF remedial_state_json
ON enrollments
FOR EACH ROW EXECUTE FUNCTION sync_enrollment_remedial_state();

INSERT INTO enrollment_remedial_states (
    enrollment_id, status, original_grade, remedial_score, remedial_grade,
    exam_date, notes, updated_at
)
SELECT e.enrollment_id,
       CASE WHEN e.remedial_state_json->>'status' IN ('pending', 'passed', 'failed', 'unavailable')
            THEN e.remedial_state_json->>'status' ELSE 'unavailable' END,
       normalization_jsonb_number(e.remedial_state_json->'originalGrade'),
       normalization_jsonb_number(e.remedial_state_json->'remedialScore'),
       normalization_jsonb_number(e.remedial_state_json->'remedialGrade'),
       CASE
           WHEN COALESCE(NULLIF(e.remedial_state_json->>'examDate', ''), NULLIF(e.remedial_state_json->>'dueDate', '')) ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$'
           THEN COALESCE(NULLIF(e.remedial_state_json->>'examDate', ''), NULLIF(e.remedial_state_json->>'dueDate', ''))::DATE
           ELSE NULL
       END,
       NULLIF(e.remedial_state_json->>'notes', ''),
       COALESCE(e.updated_at, e.created_at, CURRENT_TIMESTAMP(6))
  FROM enrollments e
 WHERE e.remedial_state_json IS NOT NULL
ON CONFLICT (enrollment_id) DO UPDATE SET
    status = EXCLUDED.status,
    original_grade = EXCLUDED.original_grade,
    remedial_score = EXCLUDED.remedial_score,
    remedial_grade = EXCLUDED.remedial_grade,
    exam_date = EXCLUDED.exam_date,
    notes = EXCLUDED.notes,
    updated_at = EXCLUDED.updated_at;

-- Link historical rows to their owning session whenever the relationship is
-- unambiguous. Legacy date/code columns remain immutable snapshots for rows
-- that predate persistent sessions or have no session match.
UPDATE attendance_records r
   SET attendance_session_id = s.session_id
  FROM enrollments e,
       attendance_sessions s
 WHERE r.enrollment_id = e.enrollment_id
   AND s.cs_id = e.cs_id
   AND s.session_date = r.session_date
   AND s.session_code = r.session_code
   AND r.attendance_session_id IS NULL;

CREATE OR REPLACE FUNCTION validate_attendance_session_reference()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    session_row RECORD;
BEGIN
    IF NEW.attendance_session_id IS NULL THEN
        RETURN NEW;
    END IF;
    SELECT s.session_date, s.session_code, s.cs_id, e.cs_id AS enrollment_cs_id
      INTO session_row
      FROM attendance_sessions s
      JOIN enrollments e ON e.enrollment_id = NEW.enrollment_id
     WHERE s.session_id = NEW.attendance_session_id;
    IF NOT FOUND THEN
        -- Leave absent-session validation to the declarative foreign key so
        -- callers retain the existing 23503 error contract.
        RETURN NEW;
    END IF;
    IF NEW.session_date IS DISTINCT FROM session_row.session_date
       OR NEW.session_code IS DISTINCT FROM session_row.session_code THEN
        RAISE EXCEPTION 'attendance record snapshot does not match its attendance session';
    END IF;
    IF session_row.cs_id IS DISTINCT FROM session_row.enrollment_cs_id THEN
        RAISE EXCEPTION 'attendance record enrollment does not belong to its attendance session class';
    END IF;
    RETURN NEW;
END
$$;

DROP TRIGGER IF EXISTS trg_validate_attendance_session_reference ON attendance_records;
CREATE TRIGGER trg_validate_attendance_session_reference
BEFORE INSERT OR UPDATE OF attendance_session_id, session_date, session_code
ON attendance_records
FOR EACH ROW EXECUTE FUNCTION validate_attendance_session_reference();

COMMENT ON COLUMN user_accounts.person_id IS
    'Canonical person identity link; display_name remains a compatibility snapshot during migration.';
COMMENT ON COLUMN students.person_id IS
    'Canonical person identity link shared with a linked account when applicable.';
COMMENT ON TABLE grading_category_period_memberships IS
    '3NF period-category relation; grading_category_periods remains a controlled compatibility cache.';
COMMENT ON TABLE enrollment_grade_breakdowns IS
    'Normalized current grade breakdown projection; enrollments.grade_components_json remains a compatibility cache.';
COMMENT ON TABLE enrollment_remedial_states IS
    'Normalized current remedial state; enrollments.remedial_state_json remains a compatibility cache until API retirement.';
