-- Persist the two approved professional-course remedial attempts separately
-- from the original enrollment grade and the legacy policy-opaque JSON.
-- Attempt order is authoritative; legacy current-state JSON is never used to
-- infer an attempt number.
CREATE TABLE IF NOT EXISTS enrollment_remedial_attempts (
    remedial_attempt_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enrollment_id INTEGER NOT NULL REFERENCES enrollments(enrollment_id)
        ON UPDATE RESTRICT ON DELETE CASCADE,
    attempt_number SMALLINT NOT NULL,
    scheduled_date DATE NULL,
    percentage NUMERIC(5,2) NULL,
    outcome TEXT NOT NULL DEFAULT 'pending',
    actor_user_id INTEGER NOT NULL REFERENCES user_accounts(user_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT uq_enrollment_remedial_attempt_number UNIQUE (enrollment_id, attempt_number),
    CONSTRAINT ck_remedial_attempt_number CHECK (attempt_number IN (1, 2)),
    CONSTRAINT ck_remedial_attempt_percentage CHECK (
        percentage IS NULL OR (percentage >= 0 AND percentage <= 100)
    ),
    CONSTRAINT ck_remedial_attempt_outcome CHECK (outcome IN ('pending', 'passed', 'failed')),
    CONSTRAINT ck_remedial_attempt_pending_score CHECK (
        (outcome = 'pending' AND percentage IS NULL)
        OR (outcome IN ('passed', 'failed') AND percentage IS NOT NULL)
    )
);

CREATE INDEX IF NOT EXISTS ix_enrollment_remedial_attempts_enrollment
    ON enrollment_remedial_attempts (enrollment_id, attempt_number);

COMMENT ON TABLE enrollment_remedial_attempts IS
    'Authoritative first/second remedial attempts; original enrollment grades remain unchanged.';
COMMENT ON COLUMN enrollment_remedial_attempts.actor_user_id IS
    'Authenticated Faculty actor who created or last recorded the attempt.';
