-- Append-only history of manual attendance corrections. attendance_records
-- keeps only the latest status; each Faculty or Secretary change to an
-- existing record adds one row here with the old and new status, the reason
-- and the actor. The original verification_method stays on the record.
CREATE TABLE IF NOT EXISTS attendance_record_corrections (
    correction_id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    record_id            INTEGER      NOT NULL REFERENCES attendance_records (record_id)
                                          ON UPDATE RESTRICT ON DELETE RESTRICT,
    previous_status      TEXT         NOT NULL,
    new_status           TEXT         NOT NULL,
    reason               VARCHAR(500) NULL,
    corrected_by_user_id INTEGER      NULL REFERENCES user_accounts (user_id)
                                          ON UPDATE RESTRICT ON DELETE SET NULL,
    corrected_by_role    VARCHAR(20)  NOT NULL,
    corrected_at         TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
);

CREATE INDEX IF NOT EXISTS idx_attendance_record_corrections_record
    ON attendance_record_corrections (record_id, corrected_at);
