-- ATT-006: the Secretary submits Excused requests; only Faculty approve or
-- reject them. A request targets one student's attendance for one session
-- day. Approval sets the record to Excused through the correction history;
-- rejection leaves the attendance unchanged. Requests are kept as history.
CREATE TABLE IF NOT EXISTS attendance_excused_requests (
    request_id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enrollment_id         INTEGER      NOT NULL REFERENCES enrollments (enrollment_id)
                                           ON UPDATE RESTRICT ON DELETE RESTRICT,
    attendance_session_id INTEGER      NULL REFERENCES attendance_sessions (session_id)
                                           ON UPDATE RESTRICT ON DELETE RESTRICT,
    record_id             INTEGER      NULL REFERENCES attendance_records (record_id)
                                           ON UPDATE RESTRICT ON DELETE RESTRICT,
    session_date          DATE         NOT NULL,
    session_code          VARCHAR(100) NULL,
    reason                VARCHAR(500) NOT NULL,
    status                TEXT         NOT NULL DEFAULT 'pending',
    requested_by_user_id  INTEGER      NOT NULL REFERENCES user_accounts (user_id)
                                           ON UPDATE RESTRICT ON DELETE RESTRICT,
    requested_at          TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    decided_by_user_id    INTEGER      NULL REFERENCES user_accounts (user_id)
                                           ON UPDATE RESTRICT ON DELETE RESTRICT,
    decided_at            TIMESTAMP(6) NULL,
    decision_note         VARCHAR(500) NULL,
    CONSTRAINT ck_attendance_excused_requests_status CHECK (status IN ('pending', 'approved', 'rejected')),
    CONSTRAINT ck_attendance_excused_requests_decision CHECK (
        (status = 'pending' AND decided_at IS NULL AND decided_by_user_id IS NULL)
        OR (status <> 'pending' AND decided_at IS NOT NULL AND decided_by_user_id IS NOT NULL))
);

-- One pending request per student and session day.
CREATE UNIQUE INDEX IF NOT EXISTS uq_attendance_excused_requests_pending
    ON attendance_excused_requests (enrollment_id, session_date, COALESCE(session_code, ''))
    WHERE status = 'pending';
CREATE INDEX IF NOT EXISTS idx_attendance_excused_requests_status
    ON attendance_excused_requests (status, requested_at DESC);
